# Tâche n°6 : les symétries

In [1]:
from pymatgen.ext.matproj import MPRester
from pymatgen import Lattice, Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view
from pymatgen.electronic_structure.core import Magmom
from pymatgen.util.string import transformation_to_string
import numpy as np

In [2]:
with MPRester("P0mh8HMc3qiSX5g1") as m:

    # Structure for material id
    structure = m.get_structure_by_material_id("mp-24504")

    # Dos for material id
    dos = m.get_dos_by_material_id("mp-24504")

    # Bandstructure for material id
    bandstructure = m.get_bandstructure_by_material_id("mp-24504")
    
    data = m.get_data("mp-24504")[0]
    cif = data.get('cif')
    spa_symmop = SpacegroupAnalyzer(structure).get_symmetry_operations()

In [3]:
#print(data)
#print(spa_symmop)

In [4]:
def toprint(sym):
    """Fonction servant à imprimer les informations relatives à une certaine opération de symétrie"""
    
    str = sym.as_xyz_string()
    print("L'équation de la symétrie est : "+str)
    print(" ")
    print("Les matrices de rotation et de translation sont : ")
    print (sym)

# Première symétrie : rotation

In [5]:
view1 = quick_view(structure, "packed")
display(view1)
view1.script('draw SYMOP 5 {atomno=2}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [6]:
Sym1 = spa_symmop[4]
toprint(Sym1)

L'équation de la symétrie est : -y, x-y, z
 
Les matrices de rotation et de translation sont : 
Rot:
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


# Deuxième symétrie : roto-inversion

In [7]:
view2 = quick_view(structure, "packed")
display(view2)
view2.script('draw SYMOP 6 {atomno=3}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [49]:
Sym2 = spa_symmop[5]
toprint(Sym2)

L'équation de la symétrie est : y, -x+y, -z
 
Les matrices de rotation et de translation sont : 
Rot:
[[ 0.  1.  0.]
 [-1.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


# Troisième symétrie : plan miroir

In [21]:
view3 = quick_view(structure, "packed")
display(view3)
view3.script('draw SYMOP 8')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [50]:
Sym3 = spa_symmop[7]
toprint(Sym3)

L'équation de la symétrie est : x, y, -z+1/2
 
Les matrices de rotation et de translation sont : 
Rot:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
tau
[0.  0.  0.5]
